# Site settings
title: James Huffaker | Code Blog
description: "Avid full stack web developer, passionate about software and learning new tools and methods."
baseurl: "" # the subpath of your site, e.g. /blog/
url:  "http://localhost:4000" # "http://jameshuffaker.com"
twitter_username: james_huffaker
github_username:  huffaker
author: "James Huffaker"

# Build settings
markdown: kramdown

# Sass settings
sass:
    sass_dir: _scss
    style: :compressed